# Let's makes some Numpy Operations
In this notebook we will see different operation types that we can perform on arrays

## Exercise 1 Universal Functions
Given an ndarray x = [4, -1, 7, 9, 3, -5] compute the sigmoid function $ y = sigmoid(x)$ which maps numbers $(-\inf +\inf) \rightarrow (0,1)$

$$ sigmoid(x) = \frac{1}{1 + e^{-x}}$$

In [ ]:
import numpy as np

## Exercise 2 Aggregation functions
Given an array x = [[2, 3, -4,], [7, 5, 9]]

Return the mean of the elements along the rows and the minimum element along the columns

In [1]:
x = np.array([[1, 7], [2, 4]])
print(x)
print(x.mean(axis=0))
print(x.mean(axis=1))

[[1 7]
 [2 4]]
[1.5 5.5]
[4. 3.]


## Exercise 3 Sorting
Given the same array as in Ex. 1, i.e., x = [4, -1, 7, 9, 3, -5], find the 3 highest values and the positions of the 2 lowest values

In [2]:
x = np.array([4, -1, 7, 9, 3, -5])
print("Original array:", x)
highest_three = np.sort(x)[-3:][::-1]
print(highest_three)

Original array: [ 4 -1  7  9  3 -5]
[9 7 4]


# Exercise 4 Broadcasting
Compute the product between the array x1 = [[0,1,2], [3,4,5]] and the array x2 = [1, 2]
Does it raises an error? How shall x2 be modified to make the operation possible?

In [3]:
x1 = np.array([[0,1,2], [3,4,5]])
x2 = np.array([1,2])
x2_reshaped = np.reshape(x2, (-1,1))
np.multiply(x1, x2_reshaped)

array([[ 0,  1,  2],
       [ 6,  8, 10]])