# Let's manipulate some arrays! 
In this notebook we will see different wasy in which we can manipulate an array

## Exercise 1 Array accessing 
Given an ndarray `x = [[3.0, 2.0, 5.0], [1.0, 4.0, 2.0], [6.0, 7.0, 8.0]]`
Return two arrays:
1) Compute the mean of the elements along the second column 
2) Retrieve the elements with values higher than 2 along the second and third rows 

In [20]:
import numpy as np

x = np.array([[3.0, 2.0, 5.0], [1.0, 4.0, 2.0], [6.0, 7.0, 8.0]])

print(x)
print("mean", np.mean(x[:, 1]))
print("higher than 2", x[1:][x[1:] > 2] )

[[3. 2. 5.]
 [1. 4. 2.]
 [6. 7. 8.]]
mean 4.333333333333333
higher than 2 [4. 6. 7. 8.]


## Exercise 2 Array accessing to update
Given the previous array x = [[3.0, 2.0, 5.0], [1.0, 4.0, 2.0], [6.0, 7.0, 8.0]]
1) set the values of the first column to 0, if they are greater than 2
2) then try to do the same for the first and third columns together. Does it work? 

In [26]:
import numpy as np

x = np.array([[3.0, 2.0, 5.0], [1.0, 4.0, 2.0], [6.0, 7.0, 8.0]])

print(x)
x[x[:, 0] > 2, 0] = 0

x[x[:, 2] > 2, 2] = 0

print(x)


[[3. 2. 5.]
 [1. 4. 2.]
 [6. 7. 8.]]
[[0. 2. 0.]
 [1. 4. 2.]
 [0. 7. 0.]]


## Exercise 3 Array concatenation and reshaping
Given two arrays x1 = [[3,1], [2,4]] and x2 = [[3, 4], [2,4], [2,5]]

Try to concatenate them vertically and then horizontally
If something does not work try to reshape the arrays so that you can concatenate (or stack) them.


In [38]:
import numpy as np

x1 = np.array([[3,1], [2,4]])
x2 = np.array([[3, 4], [2,4], [2,5]])

horizontal_concat = np.concatenate((x1, x2), axis=0)
print(horizontal_concat)

# for the vertical concat we must reshape
x1_reshaped = np.reshape(x1, (2,2,1))
x2_reshaped = np.reshape(x2, (3, 2, 1))


np.concatenate((x1_reshaped, x2_reshaped), axis=0)

[[3 1]
 [2 4]
 [3 4]
 [2 4]
 [2 5]]
[[[3]
  [1]]

 [[2]
  [4]]]


array([[[3],
        [1]],

       [[2],
        [4]],

       [[3],
        [4]],

       [[2],
        [4]],

       [[2],
        [5]]])